# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gettext}
  s.version = "2.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Masao Mutoh"]
  s.date = %q{2009-09-08}
  s.description = %q{   Ruby-GetText-Package is a GNU GetText-like program for Ruby.
   The catalog file(po-file) is same format with GNU GetText.
  So you can use GNU GetText tools for maintaining.
}
  s.email = %q{mutomasa at gmail.com}
  s.executables = ["rgettext", "rmsgfmt", "rmsgmerge"]
  s.extra_rdoc_files = [
    "ChangeLog",
     "ChangeLog-1",
     "README.rdoc"
  ]
  s.files = [
    "COPYING",
     "ChangeLog",
     "ChangeLog-1",
     "NEWS-1",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/rgettext",
     "bin/rmsgfmt",
     "bin/rmsgmerge",
     "gettext.gemspec",
     "lib/gettext.rb",
     "lib/gettext/cgi.rb",
     "lib/gettext/class_info.rb",
     "lib/gettext/core_ext/iconv.rb",
     "lib/gettext/core_ext/string.rb",
     "lib/gettext/locale_path.rb",
     "lib/gettext/mofile.rb",
     "lib/gettext/parser/erb.rb",
     "lib/gettext/parser/glade.rb",
     "lib/gettext/parser/ruby.rb",
     "lib/gettext/poparser.rb",
     "lib/gettext/textdomain.rb",
     "lib/gettext/textdomain_group.rb",
     "lib/gettext/textdomain_manager.rb",
     "lib/gettext/tools.rb",
     "lib/gettext/tools/rgettext.rb",
     "lib/gettext/tools/rmsgfmt.rb",
     "lib/gettext/tools/rmsgmerge.rb",
     "lib/gettext/translation_target.rb",
     "lib/gettext/utils.rb",
     "lib/gettext/version.rb",
     "po/bg/rgettext.po",
     "po/bs/rgettext.po",
     "po/ca/rgettext.po",
     "po/cs/rgettext.po",
     "po/de/rgettext.po",
     "po/el/rgettext.po",
     "po/eo/rgettext.po",
     "po/es/rgettext.po",
     "po/et/rgettext.po",
     "po/fr/rgettext.po",
     "po/hr/rgettext.po",
     "po/hu/rgettext.po",
     "po/it/rgettext.po",
     "po/ja/rgettext.po",
     "po/ko/rgettext.po",
     "po/lv/rgettext.po",
     "po/nb/rgettext.po",
     "po/nl/rgettext.po",
     "po/pt_BR/rgettext.po",
     "po/rgettext.pot",
     "po/ru/rgettext.po",
     "po/sr/rgettext.po",
     "po/sv/rgettext.po",
     "po/ua/rgettext.po",
     "po/vi/rgettext.po",
     "po/zh/rgettext.po",
     "po/zh_TW/rgettext.po",
     "test/README",
     "test/Rakefile",
     "test/locale/cr/LC_MESSAGES/plural.mo",
     "test/locale/da/LC_MESSAGES/plural.mo",
     "test/locale/da/LC_MESSAGES/plural_error.mo",
     "test/locale/fr/LC_MESSAGES/plural.mo",
     "test/locale/fr/LC_MESSAGES/plural_error.mo",
     "test/locale/fr/LC_MESSAGES/test1.mo",
     "test/locale/fr/LC_MESSAGES/test2.mo",
     "test/locale/ir/LC_MESSAGES/plural.mo",
     "test/locale/ja/LC_MESSAGES/npgettext.mo",
     "test/locale/ja/LC_MESSAGES/nsgettext.mo",
     "test/locale/ja/LC_MESSAGES/pgettext.mo",
     "test/locale/ja/LC_MESSAGES/plural.mo",
     "test/locale/ja/LC_MESSAGES/plural_error.mo",
     "test/locale/ja/LC_MESSAGES/rubyparser.mo",
     "test/locale/ja/LC_MESSAGES/sgettext.mo",
     "test/locale/ja/LC_MESSAGES/test1.mo",
     "test/locale/ja/LC_MESSAGES/test2.mo",
     "test/locale/ja/LC_MESSAGES/test3.mo",
     "test/locale/la/LC_MESSAGES/plural.mo",
     "test/locale/la/LC_MESSAGES/plural_error.mo",
     "test/locale/li/LC_MESSAGES/plural.mo",
     "test/locale/li/LC_MESSAGES/plural_error.mo",
     "test/locale/po/LC_MESSAGES/plural.mo",
     "test/locale/sl/LC_MESSAGES/plural.mo",
     "test/po/cr/plural.po",
     "test/po/da/plural.po",
     "test/po/da/plural_error.po",
     "test/po/fr/plural.po",
     "test/po/fr/plural_error.po",
     "test/po/fr/test1.po",
     "test/po/fr/test2.po",
     "test/po/ir/plural.po",
     "test/po/ja/npgettext.po",
     "test/po/ja/nsgettext.po",
     "test/po/ja/pgettext.po",
     "test/po/ja/plural.po",
     "test/po/ja/plural_error.po",
     "test/po/ja/rubyparser.po",
     "test/po/ja/sgettext.po",
     "test/po/ja/test1.po",
     "test/po/ja/test2.po",
     "test/po/ja/test3.po",
     "test/po/la/plural.po",
     "test/po/la/plural_error.po",
     "test/po/li/plural.po",
     "test/po/li/plural_error.po",
     "test/po/po/plural.po",
     "test/po/sl/plural.po",
     "test/test_class_info.rb",
     "test/test_gettext.rb",
     "test/test_locale_path.rb",
     "test/test_parser.rb",
     "test/test_po_generation.rb",
     "test/test_string.rb",
     "test/test_textdomain_bind.rb",
     "test/test_textdomain_multi.rb",
     "test/test_textdomain_toplevel.rb",
     "test/test_thread.rb",
     "test/test_translation_target.rb",
     "test/testlib/N_.rb",
     "test/testlib/erb.rhtml",
     "test/testlib/erb.rxml",
     "test/testlib/gettext.rb",
     "test/testlib/gladeparser.glade",
     "test/testlib/helper.rb",
     "test/testlib/multi_textdomain.rb",
     "test/testlib/ngettext.rb",
     "test/testlib/npgettext.rb",
     "test/testlib/nsgettext.rb",
     "test/testlib/pgettext.rb",
     "test/testlib/sgettext.rb",
     "test/testlib/simple.rb",
     "test/tools/files/app.pot",
     "test/tools/files/de/app.po",
     "test/tools/files/en/app.po",
     "test/tools/files/en/test.po",
     "test/tools/files/simple_1.po",
     "test/tools/files/simple_2.po",
     "test/tools/files/simple_translation.rb",
     "test/tools/files/version.po",
     "test/tools/test.pot",
     "test/tools/test_tools.rb"
  ]
  s.homepage = %q{http://gettext.rubyforge.org/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{gettext}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby-GetText-Package is a library and tools to localize messages.}
  s.test_files = [
    "test/test_thread.rb",
     "test/testlib/N_.rb",
     "test/testlib/sgettext.rb",
     "test/testlib/ngettext.rb",
     "test/testlib/multi_textdomain.rb",
     "test/testlib/npgettext.rb",
     "test/testlib/simple.rb",
     "test/testlib/helper.rb",
     "test/testlib/nsgettext.rb",
     "test/testlib/pgettext.rb",
     "test/testlib/gettext.rb",
     "test/test_string.rb",
     "test/test_class_info.rb",
     "test/test_locale_path.rb",
     "test/test_textdomain_bind.rb",
     "test/test_gettext.rb",
     "test/tools/files/simple_translation.rb",
     "test/tools/test_tools.rb",
     "test/test_parser.rb",
     "test/test_translation_target.rb",
     "test/test_po_generation.rb",
     "test/test_textdomain_multi.rb",
     "test/test_textdomain_toplevel.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<locale>, [">= 2.0.4"])
    else
      s.add_dependency(%q<locale>, [">= 2.0.4"])
    end
  else
    s.add_dependency(%q<locale>, [">= 2.0.4"])
  end
end
